### ISSUE TITLE
[static] Consider adding root variant

### ISSUE THREAD

**Issue by amouat** [chainguard-images/images#100]
The GCT distroless project has root and nonroot variants of the static image.

Whilst I think nonroot should remain the default (unlike GCT distroless, which can be a breaking change for migrating users), we may want to consider adding a variant with the user set to root e.g. `cgr.dev/chainguard/static:latest-root` and a nonroot for symmetry `cgr.dev/chainguard/static:latest-root`.

**Comment by patflynn** [comment]
this is discussed in https://github.com/chainguard-images/images/blob/main/BEST_PRACTICES.md.  Seems like we can close this out and only add root variants as needed.
