### ISSUE TITLE
php:8.2-fpm-dev php--fpm entrypoint is broken, wrong directory

### ISSUE THREAD

**Issue by melakhvision** [chainguard-images/images#1114]
### Which image/versions are related to this issue/feature request?

Hello I'm trying to use cgr.dev/chainguard/php:8.2-fpm-dev but the entrypoint is calling a wrong directory.
When I run  
```bash
docker run --rm cgr.dev/chainguard/php:8.2-fpm-dev
```
I got this error 
![error php-fpm](https://github.com/chainguard-images/images/assets/45154979/b8a93f7f-c712-4de3-b2c1-bd5b603739ad)

Reproduce
When I exec to the docker container by name 
```bah
docker exec -it ecstatic_beaver /bin/sh
```
then do ls -l inside the /usr/bin folder there is no file or folder named php-fpm. 

![no folder or file named php-fpm](https://github.com/chainguard-images/images/assets/45154979/40d33ca2-af66-428a-adb9-b8219e7dd5ac)

The why the container starts with an endless loop 
execlineb: fatal: unable to exec /usr/bin/php-fpm: No such file or directory. 
Also when I exec to the container then do 
```bash
/usr/sbin/php-fpm
```
I got php-fpm running and ready to handle connection.

![start the php-fpm](https://github.com/chainguard-images/images/assets/45154979/3acad25e-12b4-4681-9e58-963f788c0cd8)

Need to fixed 
the entrypoint of php-fpm is on /usr/sbin/php-fpm and not on /usr/bin/php-fpm

Please can you fix we need this asap.
Thank youi

**Comment by rawlingsj** [comment]
Hi @melakhvision thanks for the issue.  Indeed I've recreated the error and will fix.

**Comment by melakhvision** [comment]
Hi @rawlingsj Thank you.
Hope we can get a fix asap
And can you add please mongo php extension and enable it

Thank for your effort

**Comment by erikaheidi** [comment]
Hello @melakhvision !
We are working on a fix to the image, it should be available after the next build cycle tonight. In the meanwhile, you may overwrite the image's entry point to `/usr/sbin/php-fpm`. 

In [this repository](https://github.com/erikaheidi/wolfi-php-demo) you can find a working example of a LEMP setup using Docker Compose. 

In regards to the Mongo extension, this is currently out of scope for our base PHP images. A possible solution is to use the `php:latest-fpm-dev` image and include additional apks to [build this extension](https://www.php.net/manual/en/mongodb.installation.manual.php) if it's a requirement for your application.

**Comment by melakhvision** [comment]
Sorry I don't get for mongo php extension. 
Can you explain or give an example ?

**Comment by erikaheidi** [comment]
Update: the `php-fpm` image has been updated and the reported issue is now fixed.

About the mongo extension, this package is not available in Wolfi OS, but you can build it from source in a Dockerfile using the `php:latest-fpm` image as base, which will allow you to install additional packages needed for building PHP extensions. It is not in our roadmap right now to include the mongo extension in our PHP images. 

If you think this package should be included in Wolfi OS, I would advise you to open an issue in the [Wolfi OS](https://github.com/wolfi-dev/os) repository.

**Comment by rawlingsj** [comment]
thanks @erikaheidi and @melakhvision - closing the issue.

**Comment by melakhvision** [comment]
I see that the path of the entrypoint has been fixed.
Thank you

Can you please add the pecl php extension. It makes easy for us to add extension like mongo php and so. I try to build it from the Dockerfile and no way to get because some packages missing like musl-dev and so.

You tell above that it can't be added but not clear

**Comment by melakhvision** [comment]
@erikaheidi can you help and be more clear ?

**Comment by erikaheidi** [comment]
Hello again @melakhvision, sorry I missed your last comment. We need to evaluate this request at the Wolfi repository, because that's the main source of our packages. We have a template there for package requests, so that the whole team sees it and we can talk about it / prioritize if that's the case. You can use [this direct link](https://github.com/wolfi-dev/os/issues/new?assignees=kaniini&labels=wolfi-package-request%2Cneeds-triage&projects=&template=new-wolfi-package-request.yml&title=%5BWolfi+Package+Request%5D%3A+%24PACKAGE_NAME) to create a new issue of type **Package Request**. You can ping me in here with the link once you have created it, so that I can highlight it to the team.
