### ISSUE TITLE
question: if an image folder has multiple melange configs, how should we config?

### ISSUE THREAD

**Issue by tuananh** [chainguard-images/images#118]
if an image folder has multiple melange configs, how should we config?

**Comment by jdolitsky** [comment]
Hello, can you elaborate on what is meant by "how should we config"?

**Comment by tuananh** [comment]
like sdk image: they have sdk melange package. what if i want to have 2 melanges package for each image build, how should image.yaml look like?

https://github.com/chainguard-images/images/blob/main/images/sdk/image.yaml

**Comment by jdolitsky** [comment]
ah. i see. this is currently unsupported. it would be hard to do so with the current github actions setup... for now it must be 1 melange for 1 apko config

besides, most things should be being packaged in https://github.com/wolfi-dev/os vs. building here. Eventually we would like to stop all melange builds in this repo
