### ISSUE TITLE
Static does not build images that the documentation states it does

### ISSUE THREAD

**Issue by jsheffield-roblox** [chainguard-images/images#1189]
Hiya all thanks for your work on this. 
Noticed when reading through the documentation, the [docs for static state that it has 6 variants](https://edu.chainguard.dev/chainguard/chainguard-images/reference/static/image_specs/), but the actual terraform [does not seem to build those](https://github.com/chainguard-images/images/blob/e0320db17ac10f5303c5985228572af0f58dd256/images/static/main.tf#L22)

Testing locally, this appears to be the case:
```
$ docker pull cgr.dev/chainguard/static:latest-dev
Error response from daemon: manifest for cgr.dev/chainguard/static:latest-dev not found: manifest unknown: Unknown manifest
```

Is it intended that static images don't have dev variants? If so, would it be troublesome to make it build the dev variants? Being able to debug the image locally would be very useful without having to switch to the bash base.

**Comment by amouat** [comment]
I'll look into what's happening with the variants. But I note that `latest-dev `will effectively be the same image as `cgr.dev/chainguard/wolfi-base` in this case.

**Comment by amouat** [comment]
The page should be updated now. It is intentional not to include the -dev variant, as that's effectively wolfi-base.

That said, I'm open to arguments for creating latest-dev - if you feel strongly about it, could you open a new issue?
