### ISSUE TITLE
postgres, redis: Can not pull images by version tags

### ISSUE THREAD

**Issue by siketyan** [chainguard-images/images#1228]
### Which image/versions are related to this issue/feature request?

- cgr.dev/chainguard/postgres:15
- cgr.dev/chainguard/postgres:15.4
- cgr.dev/chainguard/redis:7

### Issue/Feature description

I can pull chainguard/postgres by `latest` tag, but `15`, `15.4`, or other version tags are not working.

```shell
$ docker pull cgr.dev/chainguard/postgres:latest
latest: Pulling from chainguard/postgres
Digest: sha256:5d3af7b0ed95cd5f032cd08403568f44728cfb79ecade74cb02f97fc8a6f2200
Status: Image is up to date for cgr.dev/chainguard/postgres:latest
cgr.dev/chainguard/postgres:latest

$ docker pull cgr.dev/chainguard/postgres:15
Error response from daemon: manifest for cgr.dev/chainguard/postgres:15 not found: manifest unknown: Unknown manifest

$ docker pull cgr.dev/chainguard/postgres:15.4
Error response from daemon: manifest for cgr.dev/chainguard/postgres:15.4 not found: manifest unknown: Unknown manifest
```

### Docker Version

```
Client:
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:32:30 2023
 OS/Arch:           darwin/arm64
 Context:           orbstack

Server: Docker Engine - Community
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:24 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.7.2
  GitCommit:        0cae528dd6cb557f7201036e9f43420650207b58
 runc:
  Version:          1.1.8
  GitCommit:        82f18fe0e44a59034f3e1f45e475fa5636e539aa
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by siketyan** [comment]
I just found https://www.chainguard.dev/unchained/scaling-chainguard-images-with-a-growing-catalog-and-proactive-security-updates 😓

**Comment by eddiezane** [comment]
@siketyan apologies you ran into this. We tried to communicate these changes extensively over the past few months to avoid breaking folks but it's hard to reach everyone.

Here's another post from today https://www.chainguard.dev/unchained/important-updates-for-chainguard-images-public-catalog-users.

Please reach out if we can help with anything like advice on migrating. My GitHub username at chainguard dot dev.
