### ISSUE TITLE
[Image Request]: ubuntu

### ISSUE THREAD

**Issue by shivamsaraswat-ikea** [chainguard-images/images#1230]
### What software would you like us to add to our image catalog? (one per issue please)

Ubuntu base image

### which versions of the containerized software do you need?

22.04

### Add some justification for why this specific image and versions are important.

We are working on an internal application which needs a secure version of ubuntu image for container.

**Comment by amouat** [comment]
Thanks for getting in touch. We use our own Linux distribution called [Wolfi](https://github.com/wolfi-dev/), so we wouldn't package Ubuntu directly. However, Wolfi is a glibc based distro that already has a large package ecosystem - there's a good chance it already has the software you use and can be a direct replacement for ubuntu.

If there's particular applications you need, please let us know and we can look into it. If you'd like to talk to someone at Chainguard, you can use https://www.chainguard.dev/contact

**Comment by amouat** [comment]
Are these separate services? You can compile the golang tools with cgr.dev/chainguard/go and put them in the static image (cgr.dev/chainguard/static). There's also a bash image (cgr.dev/chainguard/bash) and a python one (cgr.dev/chainguard/python).

If you want all this in the same image (which I wouldn't recommend) you can use cgr.dev/chainguard/wolfi-base or the bash image with a Dockerfile and `apk add` the required packages (python, go etc) into it.

**Comment by amouat** [comment]
Cool. I'm going to close this issue. If you have any specific problems with using the base image, feel free to open a new issue.
