### ISSUE TITLE
Clean up Java READMEs

### ISSUE THREAD

**Issue by eddiezane** [chainguard-images/images#1243]
The Java-adjacent images have READMEs that mention tags and examples that we have removed for the August 16th changes. We need to clean these up.

- [x] https://github.com/chainguard-images/images/blob/main/images/jdk/README.md
- [x] https://github.com/chainguard-images/images/tree/main/images/jre/README.md
- [ ] https://github.com/chainguard-images/images/tree/main/images/maven/README.md

We should also use the [default-jvm](https://github.com/wolfi-dev/os/blob/827edf994c2be961cc02b71adaebaab9b04ff662/openjdk-17.yaml#L205-L215) package paths for these images since they are installed. i.e. `/usr/lib/jvm/default-jvm`.

**Comment by amouat** [comment]
For the JRE and JDK images I think this is enough https://github.com/chainguard-images/images/pull/1244
