### ISSUE TITLE
[static] no such file or directory

### ISSUE THREAD

**Issue by dirien** [chainguard-images/images#125]
Hi,

I am using the `cgr.dev/chainguard/static:latest` in my multi-stage Dockerfile after I build a `golang` application.

When I try to run the finished image (the `docker build` runs without an error), I get following error message:

`exec /golang-server: no such file or directory`

If I change the `FROM` to `alpine:latest`, everything works as expected. No other changes in the code or Dockerfile.

Here is the content of my Dockefile.
```Dockerfile
# syntax=docker/dockerfile:1
FROM cgr.dev/chainguard/go:1.19.3 AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY *.go ./
RUN go build -o /golang-server



#FROM alpine:latest
#COPY --from=build /golang-server /golang-server
#EXPOSE 8080
#CMD ["/golang-server"]


FROM cgr.dev/chainguard/static:latest
COPY --from=build /golang-server /golang-server
EXPOSE 8080
CMD ["/golang-server"]
```

The "server" logic is in this repository: https://github.com/dirien/hello-server.git

**Comment by amouat** [comment]
There's a few things going on here.

The error isn't saying your binary isn't there, but that the underlying C library isn't there. We intentionally don't ship this library in the static image and instead expect it to be compiled into the binary. You can do this by passing some more arguments to go, but an even easier option is to try out the ko project: https://github.com/ko-build/ko. ko will take care of compiling your program and copying it into the static image.

Alternatively, you can use an image that already has the C library. You've compiled against musl (use the go:1.19.3-glibc image if you'd rather use glibc) so the [musl-dynamic](https://github.com/chainguard-images/images/tree/main/images/musl-dynamic) image will work i.e:

```
FROM cgr.dev/chainguard/musl-dynamic:latest
 ```

**Comment by tuananh** [comment]
@dirien since you dont use C so you can compile with CGO_ENABLED=0, then it will work.

RUN CGO_ENABLED=0 go build -o /golang-server

**Comment by dirien** [comment]
Hi @amouat and @tuananh,

thanks to both of you for the great feedback! I went with the `CGO_ENABLED=0` way as the `Dockerfile` way is only for the `Azure Container Registry` task, which only supports Dockerfile.

@amouat, I already have `ko` in place in this repo, huge fan of this!
