### ISSUE TITLE
[Image Request]: haproxy

### ISSUE THREAD

**Issue by curantes** [chainguard-images/images#133]
### What software would you like us to add to our image catalog? (one per issue please)

haproxy

### which versions of the containerized software do you need?

2.6.7 (latest lts release)

### Add some justification for why this specific image and versions are important.

This is a high performance reverse proxy which are commonly internet facing and would be great with a fast and high security base image like wolfi

**Comment by amouat** [comment]
Thanks! I'll add it to the list. If there's a use case behind this and you'd like to discuss more, feel free to contact me: adrian at chainguard.dev.

**Comment by tuananh** [comment]
has anyone volunteered yet? if not, i can give it a try.

**Comment by amouat** [comment]
We (Chainguard) haven't assigned anyone and I don't think we have capacity this year, so please go ahead! That would be amazing :)

**Comment by dlorenc** [comment]
Thanks for getting started on this one!
