### ISSUE TITLE
Describe the issue/request

### ISSUE THREAD

**Issue by jspeed-meyers** [chainguard-images/images#1345]
### Which image/versions are related to this issue/feature request?

`go`

### Issue/Feature description

In this overview: https://edu.chainguard.dev/chainguard/chainguard-images/reference/go/overview/

The "host architecture example" points to a file at [tests/hello/main.go](https://github.com/chainguard-images/images/blob/main/images/go/examples/hello/main.go) that does not exist any longer.

**Comment by imjasonh** [comment]
Looks like it moved to https://github.com/chainguard-images/images/blob/main/images/go/tests/hello/main.go

**Comment by jspeed-meyers** [comment]
I'm glad to put in a PR, but I need a little hand-holding. I'm intimated by the autodocs 😨 Any pointers to what file I would need to change and any gotchas?
