### ISSUE TITLE
[nginx]: unprivileged container

### ISSUE THREAD

**Issue by mathieu-benoit** [chainguard-images/images#138]
### What software would you like us to add to our image catalog? (one per issue please)

If I run the `nginx` image as unprivileged:
```
docker run -v $(pwd)/examples/hello-world/site-content:/var/lib/nginx/html -p 8080:8080 -u 1000 cgr.dev/chainguard/nginx
```
I'm getting this error because of the `-u 1000`:
```
nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)
2022/12/20 14:14:42 [emerg] 8#8: mkdir() "/var/lib/nginx/tmp/client_body" failed (13: Permission denied)
```

Also, running this `nginx` container on port `8080` doesn't work, without any error (`-p 8080:8080`).

Is it possible to support the `unprivilged` setup of `nginx` like illustrated here: https://github.com/nginxinc/docker-nginx-unprivileged/?

### Add some justification for why this specific image and versions are important.

Adoption of this image if unprivileged containers are a requirement.

**Comment by amouat** [comment]
The unprivileged user in our container is UID 10000 (not 1000). This should be documented a lot better.

**Comment by mathieu-benoit** [comment]
Thanks @amouat, it's indeed working with UID `10000`, thanks!
```
docker run -v $(pwd)/examples/hello-world/site-content:/var/lib/nginx/html -p 8080:80 -u 1000 cgr.dev/chainguard/nginx
```

Do you know why `-p 8080:8080` is not working?

**Comment by amouat** [comment]
In `-p 8080:80`, the first port is the port on the host and the second port is in the container. In the nginx.conf we've specified that nginx listens on port 80. You can override `/etc/nginx/nginx.conf` to change this to port 8080 if that works better for you.

I'm going to close this issue, as I think it's all working. However, we're working on producing a Wolfi based nginx image in the next few weeks. If you have any requirements or usability suggestions you'd like to share please get in touch: adrian@chainguard.dev (or open an issue).

**Comment by mathieu-benoit** [comment]
Sorry for not getting back to you earlier on this @amouat.

I just gave it another try like this below:
```
cat <<EOF > nginx.conf
events {}
http {
    server {
        listen                  8080;
    }
}
EOF
docker run -d \
  -v $(pwd)/nginx.conf:/etc/nginx/nginx.conf \
  -v $(pwd)/examples/hello-world/site-content:/var/lib/nginx/html \
  -p 8080:8080 \
  -u 10000 \
  cgr.dev/chainguard/nginx
```
But still have the issue in the logs:
```
nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)
2023/02/23 21:26:27 [emerg] 8#8: mkdir() "/var/lib/nginx/tmp/client_body" failed (13: Permission denied)
```
Anything I am missing?

CC: @patflynn

**Comment by amouat** [comment]
I'm sorry @mathieu-benoit, since this was opened we updated the nginx image and brought it line with our images. The UID is now 65532. I'll try to take a look now.

**Comment by mathieu-benoit** [comment]
This works indeed, I should have checked and figured out the `-u 65532`, thanks for your help on this @amouat!

**Comment by amouat** [comment]
No, we should have documented this better. I'll update the docs. You shouldn't need to set the user at all though.
