### ISSUE TITLE
Add proot to apko & sdk images?

### ISSUE THREAD

**Issue by tuananh** [chainguard-images/images#141]
wdyt about this? also, i'm curious why proot is not used by default. is there any cons?

**Comment by kaniini** [comment]
cons: performance is much slower, also proot is buggy and linux namespaces largely replace what we need from proot.

we actually plan to drop proot as soon as apko 0.7.0 lands

**Comment by kaniini** [comment]
the native building will no longer need privilege in 0.7.0
