### ISSUE TITLE
[Docs] README update: helm

### ISSUE THREAD

**Issue by erikaheidi** [chainguard-images/images#1545]
The helm image README needs an update to adhere to the latest template.

Image files: https://github.com/chainguard-images/images/tree/main/images/helm

**Comment by gnewson** [comment]
Hi, couple of questions.
Why is there a star after the Contact Chainguard statement?  Can it be removed?
Are you looking for a detailed usage section or is a minimal or even no usage section ok for a first pass given that there is no getting started guide for helm.
Thanks.

**Comment by ltagliaferri** [comment]
Hi @gnewson, you can remove the star. A first pass would be great, you can keep it lightweight
