### ISSUE TITLE
question: do we need busybox in sdk image?

### ISSUE THREAD

**Issue by tuananh** [chainguard-images/images#160]
from [apko build process doc](https://github.com/chainguard-dev/apko/blob/main/docs/build-process.md#layer-build), there's this bit

> Set the symlinks for busybox, as busybox is a single binary which determines what action to take based on the invoked path.

do we need busybox installed in `sdk` image then?

**Comment by amouat** [comment]
It is installed, both bash and busybox are pulled in by the sdk package: https://github.com/chainguard-images/images/blob/main/images/sdk/configs/wolfi.melange.yaml

**Comment by amouat** [comment]
I'll close this for the moment, but please open a new issue if something's not clear or I've misunderstood. We could change things to be more explicit about how the shell gets pulled in.
