### ISSUE TITLE
[Image Request]: aspnet image need

### ISSUE THREAD

**Issue by lemchen** [chainguard-images/images#170]
### What software would you like us to add to our image catalog? (one per issue please)

Microsoft aspnet framework 

### which versions of the containerized software do you need?

7.0

### Add some justification for why this specific image and versions are important.

Microsoft provide a Chiseled ubuntu image, but it is not good enough as you did.

**Comment by stevehipwell** [comment]
I think you'd also need at least the latest LTS version which is v6.

**Comment by amouat** [comment]
Thanks, we'll take a look at this! If you have a specific use case please get in touch (adrian@chainguard.dev) and we'll try to prioritise it.

**Comment by kaniini** [comment]
.NET and ASP.NET 7 images are now available:

`cgr.dev/chainguard/dotnet-runtime:7.0`, `cgr.dev/chainguard/aspnet-runtime:7.0`, `cgr.dev/chainguard/dotnet-sdk:7.0` :)
