### ISSUE TITLE
[Image Request]: SubstrateVM base

### ISSUE THREAD

**Issue by dlorenc** [chainguard-images/images#171]
### What software would you like us to add to our image catalog? (one per issue please)

See https://github.com/GoogleContainerTools/distroless/issues/217#issuecomment-1369358515

### which versions of the containerized software do you need?

Libz

**Comment by dlorenc** [comment]
cc @tysonkun - we can discuss here. We should be able to get libz into a base image if you can try it out!

**Comment by dlorenc** [comment]
Hey @tysonkun - I pushed some test images here:

* ghcr.io/dlorenc/images/java-static-amd64
* ghcr.io/dlorenc/images/java-static

(these are just tests so I did tags for the different architectures, default is arm64) - they should have zlib and glibc:

```shell
% docker run ghcr.io/dlorenc/images/java-static-amd64 ldconfig -p
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
20 libs found in cache `/etc/ld.so.cache'
	libz.so.1 (libc6,x86-64) => /lib/libz.so.1
	libutil.so.1 (libc6,x86-64) => /lib/libutil.so.1
	libthread_db.so.1 (libc6,x86-64) => /lib/libthread_db.so.1
	librt.so.1 (libc6,x86-64) => /lib/librt.so.1
	libresolv.so.2 (libc6,x86-64) => /lib/libresolv.so.2
	libpthread.so.0 (libc6,x86-64) => /lib/libpthread.so.0
	libnss_files.so.2 (libc6,x86-64) => /lib/libnss_files.so.2
	libnss_dns.so.2 (libc6,x86-64) => /lib/libnss_dns.so.2
	libnss_compat.so.2 (libc6,x86-64) => /lib/libnss_compat.so.2
	libnsl.so.1 (libc6,x86-64) => /lib/libnsl.so.1
	libmvec.so.1 (libc6,x86-64) => /lib/libmvec.so.1
	libmemusage.so (libc6,x86-64) => /lib/libmemusage.so
	libm.so.6 (libc6,x86-64) => /lib/libm.so.6
	libdl.so.2 (libc6,x86-64) => /lib/libdl.so.2
	libcrypt.so.1 (libc6,x86-64) => /lib/libcrypt.so.1
	libc_malloc_debug.so.0 (libc6,x86-64) => /lib/libc_malloc_debug.so.0
	libc.so.6 (libc6,x86-64) => /lib/libc.so.6
	libanl.so.1 (libc6,x86-64) => /lib/libanl.so.1
	libBrokenLocale.so.1 (libc6,x86-64) => /lib/libBrokenLocale.so.1
	ld-linux-x86-64.so.2 (libc6,x86-64) => /lib/ld-linux-x86-64.so.2
Cache generated by: ldconfig (GNU libc) stable release version 2.36
```

**Comment by tisonkun** [comment]
@dlorenc I'm reading this now. And my ID is @tisonkun, you have some typos above XD.

**Comment by dlorenc** [comment]
> @dlorenc I'm reading this now. And my ID is @tisonkun, you have some typos above XD.

Fixed! And now that you're here autocomplete works :)

**Comment by tisonkun** [comment]
```
➜  hawkeye git:(main) docker login ghcr.io                             
Username: tisonkun
Password: 
Login Succeeded
➜  hawkeye git:(main) docker pull ghcr.io/dlorenc/images/java-static
Using default tag: latest
Error response from daemon: denied
```

I'm trying to build my native image docker image with it, but it seems fail to pull. Sorry I'm not quite familiar with ghcr.io. Do you have some ideas here?

**Comment by dlorenc** [comment]
My mistake - I forgot I had to make every new image public when I push to ghcr.io - can you try again?

**Comment by tisonkun** [comment]
@dlorenc Cool! It works.

You can try my demo by cloning https://github.com/korandoru/hawkeye and run:

```
docker build . -t hawkeye-native -f Dockerfile.native
docker run -it --rm hawkeye-native
```

The software is rather simple but still a completed native image and it shows that your image meets the basic requirement to run native images produced by GraalVM 22.3.0.

**Comment by tisonkun** [comment]
... and the final image size is 22.9MB. Awesome!

**Comment by dlorenc** [comment]
Awesome! I'll get a PR pushed up here with it :)

**Comment by tisonkun** [comment]
@dlorenc Thanks. Please notify me if you release the image at some stable source. To replace `ubuntu:jammy` I guess I need some reliable source instead of an one-time image - I cannot maintain it, yes :D

**Comment by tuananh** [comment]
@dlorenc better advertise it in graalvm user group / community to get more feedbacks maybe.

**Comment by dlorenc** [comment]
The stable location for this image is now at `cgr.dev/chainguard/graalvm-native-image-base`!
