### ISSUE TITLE
cannot pull cgr.dev/chainguard/memcached

### ISSUE THREAD

**Issue by tuananh** [chainguard-images/images#180]
```
docker pull cgr.dev/chainguard/memcached
Using default tag: latest
Error response from daemon: Head "https://cgr.dev/v2/chainguard/memcached/manifests/latest": denied
```

i got the above error. is it because of the experimental flag ?

**Comment by jdolitsky** [comment]
We merged too many PRs too quickly, so we need to manually re-run them or wait til nightly build. Will comment here once it is available

**Comment by jdolitsky** [comment]
should be available now!
