### ISSUE TITLE
[Image Request]: Grafana

### ISSUE THREAD

**Issue by gerbil** [chainguard-images/images#1804]
### What software would you like us to add to our image catalog? (one per issue please)

https://github.com/grafana/grafana

### which versions of the containerized software do you need?

latest

### Add some justification for why this specific image and versions are important.

Grafana allows you to query, visualize, alert on and understand your metrics no matter where they are stored. Create, explore, and share dashboards with your team and foster a data-driven culture:

Visualizations: Fast and flexible client side graphs with a multitude of options. Panel plugins offer many different ways to visualize metrics and logs.
Dynamic Dashboards: Create dynamic & reusable dashboards with template variables that appear as dropdowns at the top of the dashboard.
Explore Metrics: Explore your data through ad-hoc queries and dynamic drilldown. Split view and compare different time ranges, queries and data sources side by side.
Explore Logs: Experience the magic of switching from metrics to logs with preserved label filters. Quickly search through all your logs or streaming them live.
Alerting: Visually define alert rules for your most important metrics. Grafana will continuously evaluate and send notifications to systems like Slack, PagerDuty, VictorOps, OpsGenie.
Mixed Data Sources: Mix different data sources in the same graph! You can specify a data source on a per-query basis. This works for even custom datasources.

**Comment by gecube** [comment]
It looks like that the grafana is already present in Chainguard catalogue

<img width="1159" alt="Screenshot 2024-01-24 at 10 42 13" src="https://github.com/chainguard-images/images/assets/2912732/7febbc80-5328-4988-8c0b-faaa077ae6b6">

@gerbil could you kindly confirm it or otherwise?

**Comment by gerbil** [comment]
As I can see - latest and latest:dev are available now in catalogue
