### ISSUE TITLE
[Image Request]: go:latest for linux/arm/v7

### ISSUE THREAD

**Issue by willnorris** [chainguard-images/images#182]
### What software would you like us to add to our image catalog? (one per issue please)

6b6cbc61406fe3125119d5b7d4a19ffa6945e483 changed the default go image from alpine/musl to wolfi/glibc.  As a result, it reduced the supported architectures to just linux/amd64 and linux/arm64.  I'm guess the alpine/musl builds ended up building for all architectures that alpine supports?

Are you intentionally limiting wolfi images to just those architectures, or would you be willing to also include linux/arm/v7?  Or should we just manually switch over to the musl versions (which is fine too, I just wanted to check).

**Comment by willnorris** [comment]
Actually one issue with us switching the musl image is that it doesn't appear to exist for specific tagged go versions?  For example, I don't think I can currently build for linux/arm/v7 with go1.19:

```
$docker pull --platform linux/arm/v7 cgr.dev/chainguard/go:1.19-musl
Error response from daemon: manifest unknown

$ docker pull --platform linux/arm/v7 cgr.dev/chainguard/go:1.19
1.19: Pulling from chainguard/go
no matching manifest for linux/arm/v7 in the manifest list entries
```

**Comment by willnorris** [comment]
I suspect that 6b6cbc61406fe3125119d5b7d4a19ffa6945e483 updated the go:1.19 image in addition to go:latest.  I'd argue that it shouldn't have.  Using `go:latest` comes with the understanding that you are living on the bleeding edge.  By choosing `go:1.19` I would expect more stability.  I think switching `go:latest` to wolfi is fine, as well as `go:1.20` and going forward, but don't change already published stable versions.

**Comment by amouat** [comment]
Thanks @willnorris. Good questions.

We did change the image to a wolfi build. The issue with producing an arm/v7 image for wolfi is that we have to build new packages and there is also a cost in setting up a new build architecture and sourcing servers (or just using qemu at a CPU cost). We could do it, but it depends on how useful it is vs the cost.

In tailscale's case, I assume you see a lot of arm/v7 due to people running home labs with rpis?

For the time being, you will need to use the musl image if you want arm/v7 support, but hopefully this will change in the future. 

Apologies about changing the go:1.19 image. I don't want to revert the change as that would cause more confusion but we should have been more careful here.

**Comment by willnorris** [comment]
Thanks, I do understand that adding arm/v7 support is a larger lift not to be done lightly.  We can switch over to another image for the time being.  It looks like there is only a `latest-musl` image, but no versioned images such as `1.19-musl`.  Do you plan to publish those tags as well, or is musl a "best effort" and the real energy is on the wolfi images?

**Comment by amouat** [comment]
It seems the tags need some work. There should be `1.19`, `1.19-musl`, `1.20`, `1.20-musl` and probably `1.20rc1` (which would currently be the same).

Both `latest` and `latest-musl` (correctly) point to 1.19, *not* 1.20. That's really not clear at the moment though. I'll try to get this sorted asap.

**Comment by willnorris** [comment]
`docker pull --platform linux/arm/v7 cgr.dev/chainguard/go:1.19-musl` is succeeding now, so I think we're in good shape.  Thanks.  Realistically, we should be able to just cross-compile our binary in a standard linux/amd64 build image, which is the direction we'll eventually go.  I think everything here is done (at least in terms of the original request), so I'll close this out.

**Comment by amouat** [comment]
Thanks @willnorris!
