### ISSUE TITLE
dev variants for base images

### ISSUE THREAD

**Issue by dlorenc** [chainguard-images/images#187]
We should include -debug variants for our base images (static, cc, glibc-dynamic) etc. These would be the same as normal but then have a shell!

**Comment by charlieegan3** [comment]
Hi, just a drive by comment to mention that the OPA project would like to make use of this for the `cgr.dev/chainguard/cc-dynamic` image. We've updated our other images to use this as the base (https://github.com/open-policy-agent/opa/pull/5540) however we still have a `-debug` image with a shell (currently based on `gcr.io/distroless/cc-debian11:debug`).

We'd like to move to a debug image which doesn't contain OpenSSL.

**Comment by patflynn** [comment]
any objections to using 'dev' since we've already started down that road?

**Comment by charlieegan3** [comment]
(Not from us!)

**Comment by charlieegan3** [comment]
Hi all, any update on this one?

**Comment by amouat** [comment]
Working on it as we speak, don't have a timeline yet. I want to standardise all tags at the same time.

**Comment by charlieegan3** [comment]
Thanks for the update @amouat and for your work on this, keep us posted!

**Comment by amouat** [comment]
We've now published a best practice guide, which includes creating "dev" variants. The next step is to apply the practices to all of our images. https://github.com/chainguard-images/images/blob/main/BEST_PRACTICES.md

**Comment by charlieegan3** [comment]
That sounds ideal 👍 thanks for sharing!

**Comment by patflynn** [comment]
couple of notes about what the overrides should be:

add deps:
- wolfi-base (busybox, apktools)

set user: root (this is probably worth discussing)

**Comment by patflynn** [comment]
[This PR ](https://github.com/chainguard-dev/apko/pull/524), should enable us to generate dev variants for our images.

**Comment by charlieegan3** [comment]
Thanks for the updates Patrick! This is looking great so far 🙂

**Comment by jdolitsky** [comment]
So we now have this file which defines a dev variant to apply wherever we want to: https://github.com/chainguard-images/images/blob/main/globals.yaml

My remaining questions are:
- What are the correct packages to be brought in for dev variants? Currently its apk-tools+bash+busybox, but should it be just wolfi-base?
- Do we still want to set user to root?
- Which images should have a dev variant? All of them?

@patflynn

**Comment by patflynn** [comment]
@amouat  @kaniini  FYI

I believe that yes it should just be wolfi-base and then a mechanism for customization for specific images (like python-dev including pip)

**Comment by patflynn** [comment]
I'm not sure about including a dev for all images but maybe yes?  @amouat thoughts?

**Comment by patflynn** [comment]
and yes to user root for dev variants. @amouat again to confirm.

**Comment by jdolitsky** [comment]
marking as done for now.

if we need to modify the global dev options (root user, etc.) its a simple change. or if we need to add a dev variant to another image, simple change

**Comment by charlieegan3** [comment]
Hey, would it be better to open another issue for the adding of a dev variant for the `cgr.dev/chainguard/cc-dynamic` image?

**Comment by jdolitsky** [comment]
@charlieegan3 - sorry we didnt get that one before. Patrick just added it in #367. Try this image:

```
cgr.dev/chainguard/cc-dynamic:latest-dev
```

If there are any issues with using it, or require another dev variant, please open another issue. Thank you!

**Comment by charlieegan3** [comment]
Amazing, thanks! 😊

**Comment by charlieegan3** [comment]
Just realised that we also need a -dev variant for static but I can open a PR for that 😊

**Comment by charlieegan3** [comment]
https://github.com/chainguard-images/images/pull/368
