### ISSUE TITLE
Should node (latest) images have a shell?

### ISSUE THREAD

**Issue by macabu** [chainguard-images/images#1969]
### Which image/versions are related to this issue/feature request?

cgr.dev/chainguard/node-lts:latest@sha256:4d282d59c135c0d4d90f1228d5bae9827da8aed37153bba3fee98f9f42d103fc

### Issue/Feature description

I was reading [this page](https://edu.chainguard.dev/chainguard/chainguard-images/debugging-distroless-images/) and it says:
> Having a package manager and the ability to log into the image to debug any issues is very important at development time, but becomes unnecessary (and less safe) when talking about production environments. That’s why we recommend using a distroless variant for production workloads.

It implied to me that the `node` images wouldn't contain a shell, like the `php` one doesn't.  
   
Are they required to have a shell for some other reason?  
  
Sorry if this has been raised before but I couldn't find the issue!

**Comment by max-allan-cgr** [comment]
Hi @macabu , 
We are actually working on removing a lot of things (like the shell) from the node images.

Thanks for the feedback!

**Comment by macabu** [comment]
Thanks for the reply, great news! 🚀

**Comment by smoser** [comment]
https://github.com/chainguard-images/images/pull/2563
