### ISSUE TITLE
Fix go image tags

### ISSUE THREAD

**Issue by amouat** [chainguard-images/images#199]
We currently advertise latest, latest-musl and 1.20.

1.20 is an rc release. We should have the following tags:

- latest, (latest-)glibc, 1.19 (all 1.19 wolfi image)
- (latest-)musl, 1.19-musl (1.19 musl image)
- 1.20, 1.20rc1, 1.20-glibc, 1.20rc1-glibc (all 1.20 wolfi image)
- 1.20-musl, 1.20rc1-musl (1.20 musl image)

**Comment by jdolitsky** [comment]
I'm not sure how we will do: 1.20-musl, 1.20rc1-musl (1.20 musl image)

I dont know if those packages are available in an Alpine repo

**Comment by amouat** [comment]
@jdolitsky yeah, good point! Just drop those.
