### ISSUE TITLE
Add .net image

### ISSUE THREAD

**Issue by amouat** [chainguard-images/images#223]
Create a .net image. See https://twitter.com/sbs0x/status/1573359024598405122

**Comment by patflynn** [comment]
Hi @tuananh, thanks for the offer. @kaniini was planning on working on this soon, let's see what she says.

**Comment by patflynn** [comment]
@kaniini has started on this.

**Comment by patflynn** [comment]
Still workin on .Net.  Depending on CNSC party could be this week or next.

**Comment by patflynn** [comment]
This issue is blocked by https://github.com/dotnet/sdk/issues/30558. Moving to Q2.

**Comment by stevehipwell** [comment]
@patflynn is this bug also present in .NET v7?

**Comment by kaniini** [comment]
At the moment our focus is on .NET 6 as it is the LTS branch.  I have not checked with .NET 7 yet.

**Comment by stevehipwell** [comment]
@kaniini I agree that LTS support should be the primary target; but if .NET 6 has a defect and the maintainers haven't offered to fix it immediately it'd be worth checking if it's still a defect in .NET 7 (which will be closer to the code for the next LTS). Also being able to test with .NET 7 would be useful even if it isn't a LTS.

AFAIK there are a number of pretty major defects in .NET v6 meaning that there are more production deployments of .NET v7 that would be expected for a non LTS version.

**Comment by kaniini** [comment]
Interesting.  I can retry my test with .NET 7 later this week.

**Comment by stevehipwell** [comment]
@kaniini it looks like the [.NET 8 preview](https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-preview-1/) should work as the announcement refers to [Build your own .NET from dotnet/dotnet](https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-preview-1/#build-your-own-net-from-dotnet-dotnet); which also suggests that this might not work on .NET 7. I'd guess if this is the case that it's unlikely that it'd be backported so maybe .NET 8 needs to be the target.

**Comment by RichiCoder1** [comment]
I think .NET 6 forward was built from `source-build`, but likely .NET 8 lowered the requirements/complexity further: https://devblogs.microsoft.com/dotnet/dotnet-6-is-now-in-ubuntu-2204/

That said, while a runtime image would be awesome, a AOT-compatible image might be simpler and backwards-compatible, though it still has decently extensive list of requirements: https://github.com/dotnet/core/blob/main/release-notes/7.0/linux-packages.md

**Comment by dlorenc** [comment]
I've managed to get 7 and 8 to build although it's not pretty. We'll get back to this in a few weeks!

**Comment by mathieu-benoit** [comment]
Indeed, great to see, thanks @kaniini!

Any chance to get the `dotnet/runtime-deps` variation too?
```
mcr.microsoft.com/dotnet/runtime        7.0.4                                   40450c453530   6 days ago    190MB
mcr.microsoft.com/dotnet/runtime-deps   7.0.4                                   b53cbd54f8b3   6 days ago    117MB
mcr.microsoft.com/dotnet/runtime        7.0.4-alpine3.17-amd64                  017bf992c17b   2 weeks ago   84.2MB
mcr.microsoft.com/dotnet/runtime-deps   7.0.4-alpine3.17-amd64                  ada21ea6f003   2 weeks ago   12.1MB
```
`dotnet/runtime-deps` allows to have a smaller container like illustrated above.

Thanks!

**Comment by kaniini** [comment]
What exactly is runtime-deps used for?  What’s the difference between it and runtime?

**Comment by mathieu-benoit** [comment]
[.NET can be published in two different modes](https://learn.microsoft.com/en-us/dotnet/core/deploying/): _framework_ (`runtime`) or _self-contained_ (`runtime-deps`). There are [pros and cons to use one or the other](https://andrewlock.net/should-i-use-self-contained-or-framework-dependent-publishing-in-docker-images/), but one attractive feature with self-contained is that you can [trim your app bundled](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-self-contained), minimizing the size of the final image.

**Comment by patflynn** [comment]
created https://github.com/chainguard-images/images/issues/423 to track the new variant request.
