### ISSUE TITLE
[Image Request]: cgr.dev/chainguard/python:3.x

### ISSUE THREAD

**Issue by lpcalisi** [chainguard-images/images#228]
### What software would you like us to add to our image catalog? (one per issue please)

more python versions

### which versions of the containerized software do you need?

3.9, 3.10

### Add some justification for why this specific image and versions are important.

Many python applications are not running well with 3.11 (syntax changes, deprecated features, etc)

**Comment by patflynn** [comment]
we should definitely do 3.10.

**Comment by strongjz** [comment]
3.10 is there now 

```
docker run -it --rm cgr.dev/chainguard/python:3.10 python --version
Python 3.10.9
```
