### ISSUE TITLE
Outdated overview for Rust image (advises to use invalid image `cc`)

### ISSUE THREAD

**Issue by polarathene** [chainguard-images/images#2314]
### Which image/versions are related to this issue/feature request?

[`cgr.dev/chainguard/rust`](https://images.chainguard.dev/directory/image/rust/overview) (_README suggests it was written or last updated in Jan 2023 when 1.67 was the latest version?_)

### Issue/Feature description

https://images.chainguard.dev/directory/image/rust/overview

> The exact image will depend on your application, but `static`, `glibc-dynamic`, or `cc` should work.
> This sample Dockerfile shows how to get a basic build up and running on `cc`.

```console
$ docker pull cgr.dev/chainguard/cc

Using default tag: latest
Error response from daemon: Head "https://cgr.dev/v2/chainguard/cc/manifests/latest": denied: {"errors":[{"code":"FORBIDDEN","message":"Forbidden"}]}
```

Potentially renamed to `cc-dynamic`?:

https://images.chainguard.dev/directory/image/cc-dynamic/overview

> This image is deprecated. Use the `glibc-dynamic` image instead which is designed to cover the same use cases.

Seems that `cc` should not be referenced in the Rust image overview?

---

There is also the "EXPERIMENTAL" label, but I see there is a draft PR already open to address removing that from this image and others.

I haven't checked if any other image overviews also reference `cc` or `cc-dynamic`, which may also need to be updated.

**Comment by amouat** [comment]
Yeah, this is wrong, I'm not sure what happened.

I'll do an update now. I'd actually recommend glibc-dynamic over cc-dynamic.
