### ISSUE TITLE
[BUG] Documentation on `pytorch-cuda12` Missing Beginning of `gcloud` Command

### ISSUE THREAD

**Issue by jspeed-meyers** [chainguard-images/images#2328]
### Which image/versions are related to this issue/feature request?

pytorch-cuda12

### Issue/Feature description

In the [pytorch-cuda12](https://github.com/chainguard-images/images/blob/main/images/pytorch-cuda12/TESTING.md#installation) documentation on testing, the first step is creating a VM with GPUs.

It is currently written as below:

```
--zone=us-central1-a \
--machine-type=n1-standard-4 \
--accelerator="type=nvidia-tesla-t4,count=2" \
--boot-disk-size=200GB \
--boot-disk-type=pd-standard \
--image-family=ubuntu-2204-lts \
--image-project=ubuntu-os-cloud \
--maintenance-policy=TERMINATE \
--restart-on-failure
```

I don't know much about GCP, but I suspect that the command should be more like:

```
gcloud compute instances create INSTANCE_NAME \
--zone=us-central1-a \
--machine-type=n1-standard-4 \
--accelerator="type=nvidia-tesla-t4,count=2" \
--boot-disk-size=200GB \
--boot-disk-type=pd-standard \
--image-family=ubuntu-2204-lts \
--image-project=ubuntu-os-cloud \
--maintenance-policy=TERMINATE \
--restart-on-failure
```

Ignore me if I'm confused and close this issue :)

@EyeCantCU

**Comment by smythp** [comment]
I actually have a fresh set of instructions for spinning up a deep learning GCP instance after working on the pytorch-cuda12 getting started. I'll do a swap out. Thanks!
