### ISSUE TITLE
Attempt to open cnn_infer failed  (libcudnn_cnn_infer.so.8 linking)

### ISSUE THREAD

**Issue by smythp** [chainguard-images/images#2532]
### Which image/versions are related to this issue/feature request?

pytorch-cuda12:latest

### Issue/Feature description

```
/usr/share/torchvision/.venv/lib/python3.11/site-packages/torch/nn/modules/conv.py:456: UserWarning: Attempt to open cnn_infer failed: handle=0 error: libcudnn_cnn_infer.so.8: cannot open shared object file: No such file or directory (Triggered internally at /tmp/build-via-sdist-qyw2z4w4/torch-2.2.1+cu121/aten/src/ATen/native/cudnn/Conv_v8.cpp:78.)
```

This may be a linking issue, see https://github.com/microsoft/WSL/issues/5663#issuecomment-1068499676

To replicate, try running the [script](https://github.com/chainguard-dev/pytorch-cuda-getting-started) for the pytorch-cuda getting started  guide with the provided data.

It seems it would be best if this were resolved before the CUDA beta launch.

**Comment by dnlfdz** [comment]
I duplicated this as https://github.com/chainguard-dev/image-requests/issues/1755 we can close this one now.
