### ISSUE TITLE
Consider publishing images to Amazon ECR Public Gallery

### ISSUE THREAD

**Issue by mandrean** [chainguard-images/images#2571]
### Issue/Feature description

The images are available on https://hub.docker.com/u/chainguard, but not on Amazon's public cache:

https://gallery.ecr.aws/chainguard

Consider publishing them there as well? Great free option for users who easily get rate-limited on DH:

https://docs.aws.amazon.com/AmazonECR/latest/public/public-getting-started.html

**Comment by amouat** [comment]
I believe we are looking into this! I can't say anything about timeline.

**Comment by mandrean** [comment]
Thanks!
