### ISSUE TITLE
Apex not included in NeMo image

### ISSUE THREAD

**Issue by smythp** [chainguard-images/images#2578]
### Which image/versions are related to this issue/feature request?

nemo:latest

### Issue/Feature description

We might need Apex in the NeMo image. The Megatron NVIDIA models can't be run without it. 

```
[NeMo W 2024-04-25 14:47:17 nemo_logging:393] Apex was not found. Please see the NeMo README for installation instructions: https://github.com/NVIDIA/apex
    Megatron-based models require Apex to function correctly.
```

Can replicate by running the quickstart script currently in the nemo tests folder.

**Comment by dnlfdz** [comment]
I duplicated this as an image request in https://github.com/chainguard-dev/image-requests/issues/1756. We can close this now.
