### ISSUE TITLE
[Image Request]: node image with bash?

### ISSUE THREAD

**Issue by kastl-ars** [chainguard-images/images#2742]
### What software would you like us to add to our image catalog? (one per issue please)

I found the chainguard:node image and could successfully base my own image on it. Except that it won't run, as the application's start scripts are bash-based, while the node image only contains POSIX sh.

As per design, the node image does not contain a apk package manager, so it is not possible to just install bash in it.

As there is a lot of thought going into the node image I do not think it is wise to replicate that and start from an image with a package manager.

So, as a proposal, would it be possible to add a flavor of the node image with bash included?

(I do not yet understand the build process enough to judge if this means maintaining a copy of the node image configuration or if this could easily be extended)

Thanks in advance
Johannes

**Comment by amouat** [comment]
If you use the `node:latest-dev` image you should find apk is included and you can install bash.

**Comment by kastl-ars** [comment]
Thanks for the info, Adrian. But isn't that an anti-pattern? Then I'll end up with an image containing apk?

**Comment by amouat** [comment]
Sorry, I just saw this. I wouldn't say it's an anti-pattern, but you will have apk, yes.

It's not ideal from a security perspective, but you've already moved away from that by adding bash. The image should still be free of known-vulns, so I don't see it as a major issue. You could also build your own image with apko.

**Comment by kastl-ars** [comment]
Thanks for your reply. In the meantime I found that the requirement for bash was just due to some scripts that make node able to handle signals, which I could replace with tini or dumb-init. And I built my own image with bash, just in case.

Hence closing this...
