### ISSUE TITLE
"denied: Unable to write blob sha256:

### ISSUE THREAD

**Issue by spawar-apex** [chainguard-images/images#2845]
### Which image/versions are related to this issue/feature request?

Hi Everyone,

I am writing to raise a support ticket regarding an issue I am encountering while using the Wolfi image in my Dockerfile. Specifically, I am facing with an error message saying `"denied: Unable to write blob sha256:aae52d44a2a536e3de1897560bf1f05a87d52bcc98b5f68d8af99fb676143e316836.. Pushing failed. Exiting ..."` and despite troubleshooting on my end, I have been unable to resolve the issue.

Here are the details of the problem:

Issue: Unable to upload blob
Environment: Using Wolfi image in Dockerfile
Steps Taken: I have reviewed my Dockerfile configurations, checked network connectivity, and examined relevant documentation, but the problem persists.

Could you please share regarding this matter? If additional information or logs are needed to diagnose and resolve the issue, please let me know, and I will gladly provide them.

Thank you in advance & appreciate your time.

**Comment by spawar-apex** [comment]
This is happening when we push image to Google Container Registry. The notable thing is when I use other container images for.eg Python or Alpine, it works but when I try to use `Wolfi`, it throws an error.

Could you please share thoughts here?

**Comment by agis** [comment]
@spawar-apex have you got to the bottom of it?
