### ISSUE TITLE
Reenable Node 16 Image

### ISSUE THREAD

**Issue by henrysachs** [chainguard-images/images#287]
I would appreciate if we could we reenable the build of the node 16 image. Its still LTS in the node universe and a lot of tools build on it. Currently the docs also only list the latest and the node 19 tags even though the node 18 images exist. Maybe chainguard could add the node 18 images to the docs and also they are missing in the image.yaml file if I'm reading it correctly. I'm still new to chainguard, but would love to integrate it into my architecures. 

BTW: what are good beginner docs to get started building own images? As I would need an image containing node and git 😅

**Comment by tuananh** [comment]
images project use apko to build image

you can start here https://github.com/chainguard-dev/apko/blob/main/docs/apko_file.md
this docs describe the yaml file you find in configs folder of each image.

**Comment by amouat** [comment]
Thanks @henrysachs!

I'm looking into this. It's borderline as Node 16 is in maintenance, not LTS, but if a lot of projects depend on it, we will look at making an exception. Are there any projects in particular you were thinking of?

When you talk about the docs not mentioning Node 18, what do you mean? I see the tag listed here https://github.com/chainguard-images/images/tree/main/images/node, but it's possible that was broken when you looked at it. Or is it the body text you were thinking of?

**Comment by henrysachs** [comment]
yeah the tag listing was broken when I had a look at it. I am using the AWS CDK to deploy my infrastructure and they are currently on node 16. Amazon Linux 2 as an OS has also some limitation that they are currently on GLIBC 2.7 IIRC and node 18 needs 2.8.

**Comment by amouat** [comment]
The versions of images we make available is part of a larger conversation we're having internally. For the moment, we're going to pause builds of the node 16 image.

That being said, the wolfi node-16 package isn't going anywhere and will continue to be updated. You also mention the need to add git, so I think the best solution for you is to build your own node image with apko. In this case, you should be able to copy the [node-19 apko config](https://github.com/chainguard-images/images/blob/main/images/node/configs/19.apko.yaml), change it to version 16 and also add in the git packages. The packages section would then look like:

```
...
  packages:
    - busybox
    - ca-certificates-bundle
    - nghttp2
    - nodejs-16
    - git
    - wolfi-baselayout
...
```

You can find instructions on using apko here https://edu.chainguard.dev/open-source/apko/getting-started-with-apko/

I hope that helps. If you'd like to discuss more, please feel free to e-mail me, I think there's an address on my profile and my chainguard e-mail is my first name (at) chainguard.dev
