### ISSUE TITLE
Nginx Read Only File System

### ISSUE THREAD

**Issue by henrysachs** [chainguard-images/images#288]
A lot of Security people recommend running Images in Kubernetes or other Hypervisors in a read-only mode. [one example](https://docs.bridgecrew.io/docs/bc_k8s_21)
When trying to run the nginx image in read only mode like this: 

```
docker run -it -p8080:8080 --read-only --tmpfs /tmp cgr.dev/chainguard/nginx:latest
```

I receive the following error:

```
s6-svscan: fatal: unable to mkdir .s6-svscan: Read-only file system
```

**Comment by tuananh** [comment]
related ? https://github.com/chainguard-dev/apko/issues/497

**Comment by jdolitsky** [comment]
> related ? [chainguard-dev/apko#497](https://github.com/chainguard-dev/apko/issues/497)

This should not be related since we are using a pinned version of apko before that issue (497)

This may be able to be solved by creating this directory ahead of time in apko yaml, unsure about the inner workings of s6

**Comment by kaniini** [comment]
Use `docker run -it -p8080:8080 --read-only --tmpfs /tmp --tmpfs /sv cgr.dev/chainguard/nginx:latest` to allow the supervisor to manage its state.

**Comment by mathieu-benoit** [comment]
Same issue here.

**Comment by mathieu-benoit** [comment]
Wondering if there is anything to reuse from this section below from the [`nginx-unprivileged` container image](https://github.com/nginxinc/docker-nginx-unprivileged/blob/main/Dockerfile-alpine-slim.template#L109):
```
# implement changes required to run NGINX as an unprivileged user	
RUN sed -i 's,listen       80;,listen       8080;,' /etc/nginx/conf.d/default.conf \	
    && sed -i '/user  nginx;/d' /etc/nginx/nginx.conf \	
    && sed -i 's,/var/run/nginx.pid,/tmp/nginx.pid,' /etc/nginx/nginx.conf \	
    && sed -i "/^http {/a \    proxy_temp_path /tmp/proxy_temp;\n    client_body_temp_path /tmp/client_temp;\n    fastcgi_temp_path /tmp/fastcgi_temp;\n    uwsgi_temp_path /tmp/uwsgi_temp;\n    scgi_temp_path /tmp/scgi_temp;\n" /etc/nginx/nginx.conf \	
# nginx user must own the cache and etc directory to write cache and tweak the nginx config	
    && chown -R $UID:0 /var/cache/nginx \	
    && chmod -R g+w /var/cache/nginx \	
    && chown -R $UID:0 /etc/nginx \	
    && chmod -R g+w /etc/nginx	

```

**Comment by amouat** [comment]
Oh, could be! Thanks @mathieu-benoit. I'm also not sure the supervisor process is strictly necessary.

**Comment by patflynn** [comment]
@amouat this looks like P1, does that sound right?

**Comment by amouat** [comment]
(tl;dr: you should be able to get this working now with some experimentation and using `-v` (not `--tmpfs`)

I'm working on this at the moment. s6 has been removed from the image, so that no longer causes a problem. Unfortunately `--tmpfs` doesn't work for some reason, and the non-ro directories have to be explicitly mounted.

I intend for our default image to use a non-privileged user, which may result in some differences to the official image. Our image currently uses different directories for some files and I'm still trying to get to the bottom of that difference.

**Comment by mathieu-benoit** [comment]
With:
```
docker run -d \
    -p 8080:8080 \
    -u 65532 \
    --cap-drop=ALL \
    --read-only \
    --tmpfs /tmp \
    cgr.dev/chainguard/nginx:next
```
I'm still getting this error in the logs:
```
nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (30: Read-only file system)
2023/04/27 01:51:13 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
2023/04/27 01:51:13 [emerg] 1#1: mkdir() "/var/lib/nginx/tmp/client_body" failed (30: Read-only file system)
```

Same with `-v /tmp`.

**Comment by amouat** [comment]
#478 takes care of this and includes instructions for running read-only. The alert message should be gone now.

Thanks to everyone for the bug report and help to debug.

Please open a new issue if there any further problems (note it will take a moment for the new image to build & upload).
