### ISSUE TITLE
Bun is outdated

### ISSUE THREAD

**Issue by notramo** [chainguard-images/images#2923]
### Which image/versions are related to this issue/feature request?

`bun:latest`

### Issue/Feature description

There is a [Bun](https://bun.sh) image at https://images.chainguard.dev/directory/image/bun/versions

However, the version is `1.1.0` which is months old from [April 1, 2024](https://bun.sh/blog/bun-v1.1) (no, it was not an april's fool joke).
Also, the logo is wrong, it's not the bun logo at the Chainguard webpage.

I'm wondering if it's been removed (given the `bun` directory can not be found in this repo)? In this case, it would be useful to indicate it at https://images.chainguard.dev/directory/image/bun/versions

**Comment by xnox** [comment]
Bun image has been re-instated and is now up to date https://images.chainguard.dev/directory/image/bun/versions

**Comment by notramo** [comment]
Yes, it's up to date now, but the logo is still wrong, at least on Firefox.
