### ISSUE TITLE
aspnet runtime image didn't get updated to .net 9

### ISSUE THREAD

**Issue by tvdias** [chainguard-images/images#2931]
### Which image/versions are related to this issue/feature request?

aspnet-runtime (currently on .net 8)

### Issue/Feature description

.net 9 is out and dotnet sdk and runtime images already support it

**Comment by xnox** [comment]
```console
$ docker run --pull=always --rm -ti --entrypoint apk cgr.dev/chainguard/aspnet-runtime:latest-dev list --installed | grep aspnet
latest-dev: Pulling from chainguard/aspnet-runtime
Digest: sha256:ab268b122cf38d289edda912396e3c0f231a921f463428e118cd7bf0c9178501
Status: Image is up to date for cgr.dev/chainguard/aspnet-runtime:latest-dev
aspnet-9-runtime-9.0.0-r0 x86_64 {dotnet-9} (MIT) [installed]
```

https://github.com/chainguard-images/images/commit/0fc98df373e67428e20bed37c32fcc958ccf2e45

This is now resolved! Thank you for pointing this out & helping to fix it.
