### ISSUE TITLE
Latest images pulled from Docker registry are out of date

### ISSUE THREAD

**Issue by ltagliaferri** [chainguard-images/images#2941]
### Which image/versions are related to this issue/feature request?

redis-cluster-bitnami

### Issue/Feature description

_Transferring [this issue](https://github.com/chainguard-dev/edu/issues/1785) over from edu, as reported by [keatsk](https://github.com/keatsk)_

When I pulled the latest redis-cluster-bitnami image today (26-Aug-2024) using:
docker pull cgr.dev/chainguard/redis-cluster-bitnami:latest
I get an image from 5 months ago with a large number of vulnerabilities.

Is there a problem with your publishing pipeline?

Thanks in advance.

**Comment by xnox** [comment]
Hi,

Builds available to customers were successful during the mentioned time period

https://images.chainguard.dev/directory/image/redis-cluster-bitnami/versions

At this point in time, it is not possible to troubleshoot this.

If you have any queries about any other images do let us know by opening a new issue!
