### ISSUE TITLE
openscap image does not contain oscap-docker package

### ISSUE THREAD

**Issue by Jiri-Stary** [chainguard-images/images#2948]
### Which image/versions are related to this issue/feature request?

    I see that openscap docker is not supported by the current image, would it be possible to add it ? 
    
    looking on the image code the dependency is excluded - see below:
    
        # oscap-docker hard codes /usr/bin/python3 as the interpreter
        https://github.com/chainguard-images/images/blob/808e85c8cbdcf3f2a69931a08ab230757efda0f2/images/openscap/config/main.tf#L22

**Comment by jakeva** [comment]
@Jiri-Stary The issue with the `oscap-docker` package should now be resolved as per [this PR](https://github.com/wolfi-dev/os/pull/37505) that was merged a few days ago. Could you pull the latest build of `openscap` and give it another try? Let me know if you continue to run into the issue.
