### ISSUE TITLE
`nginx:alpine-slim` is smaller than `cgr.dev/chainguard/nginx`, anything to adopt here to get same or better size?

### ISSUE THREAD

**Issue by mathieu-benoit** [chainguard-images/images#305]
### Which image/versions are related to this issue/feature request?

`cgr.dev/chainguard/nginx`

### Issue/Feature description

`nginx:alpine-slim` is smaller than `cgr.dev/chainguard/nginx`: 
```
REPOSITORY                    TAG           IMAGE ID       CREATED       SIZE
cgr.dev/chainguard/nginx      latest        347a73fb3cdb   4 hours ago   20.4MB
nginx                         alpine        2bc7edbc3cf2   13 days ago   40.7MB
nginx                         alpine-slim   c59097225492   13 days ago   11.5MB
```

Anything to adopt here to get same or smaller size?

FYI: https://github.com/nginxinc/docker-nginx/blob/master/Dockerfile-alpine-slim.template

**Comment by mathieu-benoit** [comment]
Complementary information:

`syft cgr.dev/chainguard/nginx`:
```
 ✔ Loaded image            
 ✔ Parsed image            
 ✔ Cataloged packages      [26 packages]
NAME                    VERSION      TYPE 
ca-certificates-bundle  20220614-r4  apk   
execline                2.9.2.1-r0   apk   
glibc                   2.37-r1      apk   
glibc-locale-posix      2.37-r1      apk   
libcrypto3              3.0.8-r0     apk   
libgcc                  12.2.0-r9    apk   
libssl3                 3.0.8-r0     apk   
libstdc++               12.2.0-r9    apk   
nginx                   1.23.3-r1    apk   
pcre                    8.45-r0      apk   
s6                      2.11.3.0-r0  apk   
wolfi-baselayout        20230201-r0  apk   
zlib                    1.2.13-r3    apk
```

`syft nginx:alpine-slim`:
```
 ✔ Pulled image            
 ✔ Loaded image            
 ✔ Parsed image            
 ✔ Cataloged packages      [20 packages]
NAME                    VERSION      TYPE   
alpine-baselayout       3.4.0-r0     apk     
alpine-baselayout-data  3.4.0-r0     apk     
alpine-keys             2.4-r1       apk     
apk-tools               2.12.10-r1   apk     
busybox                 1.35.0       binary  
busybox                 1.35.0-r29   apk     
busybox-binsh           1.35.0-r29   apk     
ca-certificates-bundle  20220614-r4  apk     
libc-utils              0.7.2-r3     apk     
libcrypto3              3.0.8-r0     apk     
libintl                 0.21.1-r1    apk     
libssl3                 3.0.8-r0     apk     
musl                    1.2.3-r4     apk     
musl-utils              1.2.3-r4     apk     
nginx                   1.23.3-r1    apk     
pcre2                   10.42-r0     apk     
scanelf                 1.3.5-r1     apk     
ssl_client              1.35.0-r29   apk     
tzdata                  2022f-r1     apk     
zlib                    1.2.13-r0    apk
```

**Comment by hown3d** [comment]
The nginx package of the image is built using [melange](https://github.com/chainguard-dev/melange/) in the [wolfi-dev/os](https://github.com/wolfi-dev/os/) repository.
You can check the dependencies and how it's build here: https://github.com/wolfi-dev/os/blob/main/nginx.yaml

My first guess is that the wolfi package contains perl while the nginx:alpine-slim image doesn't contain perl.

**Comment by mathieu-benoit** [comment]
Thanks for the pointer, @hown3d.

Do you know why perl is required?

Do you think I should file this issue/question in the [wolfi-dev/os](https://github.com/wolfi-dev/os/) repository instead of here?

**Comment by kaniini** [comment]
Perl is used to build an optional module not included in the image.  You are comparing a musl image to a glibc image, the size differential is due to that.  But [container sizes miss the point](https://www.chainguard.dev/unchained/image-sizes-miss-the-point), instead you should look at the number of software components included in the image, which syft shows is much less for the nginx one we provide.  However, as nginx can handle running as PID 1, we might want to consider removing the s6 supervisor here, since Docker and k8s will supervise the entire container anyway.

**Comment by hown3d** [comment]
I'm not 100% sure, but iirc nginx has the possibility to work with perl scripts.
You should probably open the issue in the wolfi repository or even add a PR for a "nginx-perless" package.

**Comment by mathieu-benoit** [comment]
RE: nginx-perless, wondering if it should be the other way around: nginx + nginx-perl, like defined here: https://registry.hub.docker.com/_/nginx/.

RE: supervisor/s6 to remove, it was also mentioned here too: https://github.com/chainguard-images/images/issues/288#issuecomment-1445860422.
