### ISSUE TITLE
Add dataplaneapi binary to haproxy image

### ISSUE THREAD

**Issue by tylerauerbeck** [chainguard-images/images#308]
### Which image/versions are related to this issue/feature request?

cgr.dev/chainguard/haproxy

### Issue/Feature description

A number of other upstream `haproxy` images come bundled with ancillary haproxy tooling (such as `dataplaneapi`). This is particularly useful for cases where we're trying to programmatically interact with haproxy. Is this something that could be included in this image? Or is it left to the user to add these additional features?

Obviously this can be accomplished by using this as a base image to build from, however it seems like it would be useful to add to achieve parity with other upstream images.

**Comment by dlorenc** [comment]
I think we can either add it here or make another variant with it!

**Comment by kaniini** [comment]
We would just need to add it to the haproxy package in Wolfi, I guess.

**Comment by tuananh** [comment]
Add me add a wolfi pkg for this and then i'll do a subsequent pr in images repo.

**Comment by tuananh** [comment]
> We would just need to add it to the haproxy package in Wolfi, I guess.

would you prefer to add it to haproxy package?

**Comment by tuananh** [comment]
now that dataplaneapi package is merged. should we add dataplaneapi directly to the latest image or create a new image variant?

**Comment by dlorenc** [comment]
> now that dataplaneapi package is merged. should we add dataplaneapi directly to the latest image or create a new image variant?

I don't think we have a firm rule here - would most users expect it to be present?

**Comment by patflynn** [comment]
Based on https://hub.docker.com/r/haproxytech/haproxy-alpine we're going to include the dataplaneapi in the default image.
