### ISSUE TITLE
include curl in go image?

### ISSUE THREAD

**Issue by joemiller** [chainguard-images/images#350]
### Which image/versions are related to this issue/feature request?

go, all versions.

### Issue/Feature description

It would be useful to have curl available in the go image. Curl is one of the recommended ways to [install golangci-lint](https://golangci-lint.run/usage/install/).

A multi-stage docker image then could:
- install a specific version of golangci-lint
- run the linter
- `go test ./...`
- and finally `go build`

This would allow for having multi-stage builds that fully utilize chainguard images.

It is possible to `go install` golangci-lint but this can be rather slow and it is not recommended by the golangci-lint authors.

**Comment by joemiller** [comment]
@kaniini I thought about this too. In my experience I have seen a lot of opinions on golangci-lint. Some projects will just install latest in CI and other prefer to pin to versions. My own anecdotal experience/guess says the community splits close to 50/50 on the topic (wild guess).

**Comment by joemiller** [comment]
another workaround is simply copying the `curl` binary into the build stage, eg:

```dockerfile
FROM cgr.dev/chainguard/curl:latest AS curl

FROM cgr.dev/chainguard/go:1 AS builder

COPY --from=curl /usr/bin/curl /usr/bin/curl
# ...
```

**Comment by dlorenc** [comment]
One quick note - we do have golangci-lint already packaged in Wolfi: https://github.com/wolfi-dev/os/blob/main/golangci-lint.yaml

That means you can do something like:

```Dockerfile
FROM cgr.dev/chainguard/go:latest-dev
RUN apk add golangci-lint
```
