### ISSUE TITLE
Request: can you add the `sh` to the glibc version of the git image?

### ISSUE THREAD

**Issue by l-qing** [chainguard-images/images#351]
### Which image/versions are related to this issue/feature request?

Image: `cgr.dev/chainguard/git:latest-glibc`

### Issue/Feature description

Your images are excellent! 

Tekton's pipelines also use your git image as a base.
Ref: https://github.com/tektoncd/pipeline/pull/5542/files.
When using your git image in Tekton, a `sh` script is executed, therefore, sh is required.

However, there is a known issue with the DNS resolver in the default Alpine version, as mentioned in this issue: https://github.com/kubernetes/kubernetes/issues/64924.
So, I prefer to use the glibc version of the image.

The base image `cgr.dev/chainguard/git:latest` now includes sh, but the glibc version does not. 
Hence, I would like to request you to add `sh` to the glibc version of the image.

**Comment by l-qing** [comment]
Commands similar to rm and echo may also be needed.
It would be best if it could be as compatible as the basic version of the Git image.

**Comment by rawlingsj** [comment]
It looks like the alpine-release package depends on apk-tools and busybox at runtime https://git.alpinelinux.org/aports/tree/main/alpine-base/APKBUILD#n14 whereas wolfi's version of this doesn't https://github.com/wolfi-dev/os/blob/6dac7389131f99958531f33b86d947a809b99f74/wolfi-baselayout.yaml#L8-L9.

So if I have this right, we could add a `-dev` subvariant (e.g. like [this](https://github.com/chainguard-images/images/blob/4705037b1dff7f9ed0e5bd088251b75e55b24d62/images/jdk/image.yaml#L9-L12)) for the wolfi based git images which would include these https://github.com/chainguard-images/images/blob/main/globals.yaml and I think then provide parity with the alpine version.  

I wonder if this is the right way to go?  Then you could switch to `cgr.dev/chainguard/git:latest-glibc-dev`?
