### ISSUE TITLE
[Image Request]: go 1.20.3

### ISSUE THREAD

**Issue by willnorris** [chainguard-images/images#424]
### What software would you like us to add to our image catalog? (one per issue please)

update [go](https://github.com/chainguard-images/images/tree/main/images/go) to 1.20.3

### which versions of the containerized software do you need?

1.20.3

### Add some justification for why this specific image and versions are important.

go 1.20.3 [is a security fix](https://groups.google.com/g/golang-announce/c/Xdv6JL9ENs8) that patches four CVEs in the stdlib.  It'd be great to have that available in the chainguard go images soon.

**Comment by amouat** [comment]
I think this is done.

**Comment by dlorenc** [comment]
For reference, this was done a week ago: https://github.com/wolfi-dev/os/pull/1057
