### ISSUE TITLE
[Image Request]: bank-vaults

### ISSUE THREAD

**Issue by tuananh** [chainguard-images/images#429]
### What software would you like us to add to our image catalog? (one per issue please)

https://github.com/banzaicloud/bank-vaults

ghcr.io/banzaicloud/bank-vaults

### Add some justification for why this specific image and versions are important.

- quite popular project (1k8 stars)
- k8s vault operator among other things
- go project, relatively easy to package in Wolfi

**Comment by gecube** [comment]
Hi! Thanks for raising this ticket! I also like to add my 👍 

The image we are using is ghcr.io/banzaicloud/bank-vaults:1.19.0

**Comment by tuananh** [comment]
> Hi! Thanks for raising this ticket! I also like to add my 👍
> 
> The image we are using is ghcr.io/banzaicloud/bank-vaults:1.19.0

i'll create a PR for this. bank-vaults is already packaged for wolfi so this should be straight forward I hope.

@gecube fyi: bank-vaults recently move the repo to https://github.com/bank-vaults/bank-vaults . There's newer release over there
