### ISSUE TITLE
fluent-bit helm install test failing

### ISSUE THREAD

**Issue by jdolitsky** [chainguard-images/images#431]
see https://github.com/chainguard-images/images/actions/workflows/k8s-tests.yaml

**Comment by tuananh** [comment]
I will take a look at this later this week

**Comment by dlorenc** [comment]
I did some investigation. The helm chart injects a new config file that configures the systemd plugin, which crashes because we don't have systemd-dev available during compilation.

**Comment by dlorenc** [comment]
https://github.com/wolfi-dev/os/pull/1239 and https://github.com/wolfi-dev/os/pull/1228 should fix this.

**Comment by dlorenc** [comment]
Yeah the config file needs the linked wolfi package updates as well. Once those go in we should be good

**Comment by jdolitsky** [comment]
fixed
