### ISSUE TITLE
PostgreSQL encoding is `SQL_ASCII` instead of `UTF-8` 

### ISSUE THREAD

**Issue by wilsonehusin** [chainguard-images/images#513]
### Which image/versions are related to this issue/feature request?

cgr.dev/chainguard/postgres@sha256:405031c3608549b5aed1069774ba7072b1ff8e2d0a42da648bec56c29ff9a10f

### Issue/Feature description

I swapped an existing usage of Docker library's Postgres image and expecting things to mostly work, but somehow encoding isn't playing along. Then I found out that Docker library's PostgreSQL image uses `UTF-8` encoding out of the box, but Chainguard's is on `SQL_ASCII`.

I'd love for the defaults to match and support the experience of just swapping images, but at the very least some instructions on getting UTF-8 or migrating from Docker library's image would be appreciated!

**Comment by wilsonehusin** [comment]
Looks like setting `LC_ALL=en_US.UTF-8` did the trick!

**Comment by dlorenc** [comment]
We should be able to default to this!

**Comment by imjasonh** [comment]
Does someone want to send a PR to set this default? If so assign me and I'll approve it.

**Comment by wilsonehusin** [comment]
> Does someone want to send a PR to set this default? If so assign me and I'll approve it.

@imjasonh I put up #523 with my best understanding of how contributions on this project works. Let me know if there is anything else I can do to conform with the project's convention!
