### ISSUE TITLE
/usr/local/bin no longer in path

### ISSUE THREAD

**Issue by ecordell** [chainguard-images/images#515]
### Which image/versions are related to this issue/feature request?

I only checked `static` and `busybox`.

### Issue/Feature description

Binaries that I used to run from `/usr/local/bin` could no longer be found in the path after I rebuilt with base images that included the changes in https://github.com/chainguard-images/images/pull/511

I can manually add it back to the path, but I thought I'd raise this here in case it was an unintended side-effect.

**Comment by imjasonh** [comment]
Marking this as fixed. We'll have a postmortem to share, probably next week.
