### ISSUE TITLE
nginx image due for major update

### ISSUE THREAD

**Issue by emtunc** [chainguard-images/images#539]
### Which image/versions are related to this issue/feature request?

nginx

### Issue/Feature description

Just putting this on the radar in case it has been forgotten - the nginx image is due for a major, breaking change as per the readme https://github.com/chainguard-images/images/tree/main/images/nginx

**Comment by amouat** [comment]
Thanks @emtunc! We hadn't forgotten, we were just double checking the PR. It's merged now but will take some time for the new image to be built.
