### ISSUE TITLE
Add documentation about musl/glibc usage for images

### ISSUE THREAD

**Issue by iammathew** [chainguard-images/images#624]
### Which image/versions are related to this issue/feature request?

node

### Issue/Feature description

Currently it's hard to know if an image uses glibc or musl under the hood.
According to the documentation the images mostly use wolfi nowadays, but wolfi claims to support both, so i'm a bit unsure if it actually uses musl or glibc (node images in this case).

For images like git, there are are 2 different versions available which clearly state in the documentation that one uses glibc (wolfi).

It would be nice to have this documented somewhere easily accessible :)

**Comment by imjasonh** [comment]
I'll make sure we document this better.

In the meantime, Wolfi based images are all glibc except for images that are explicitly musl (musl-dynamic for example)
