### ISSUE TITLE
Reproducible `static` image

### ISSUE THREAD

**Issue by brancz** [chainguard-images/images#638]
### Which image/versions are related to this issue/feature request?

The `static` image.

### Issue/Feature description

We would like to use the static base image for our Go-based static binaries, however, we use renovate bot to update underlying SHAs to latest, and as far as I can tell the image gets rebuilt every day, but the content is identical except for the date label on the container image.

Our own container image builds are byte-by-byte reproducible (so long as the base image doesn't change hence why we pin via SHA) so having the base image change for no good reason weakens our reproducibility approach.

I can't say for sure if the date label is the only thing, but bottom line, I would love it if the static image was only updated if there is actually a material change to the content of the image.

**Comment by imjasonh** [comment]
This is definitely a goal of ours. We believe the main source of change is the build date, and have plans to make images' build dates based on the build dates of constituent packages (and the apko config file). This should mean the static image, which purposefully contains almost nothing that changes, will rarely change.

I don't have a solid timeline for this to share, especially for the static image which is our most used image, but stay tuned for more changes, which produce fewer changes ;)

**Comment by brancz** [comment]
Happy to test whenever you have something!

**Comment by imjasonh** [comment]
This is rolled out now!

The `static` image for example claims to have been built June 5th, since that's the latest build date of its constituent packages:

```
$ crane config cgr.dev/chainguard/static | jq -r .created
2023-06-05T10:34:41Z
```

The image has been rebuilt more than a few times since then, but since the packages haven't been updated there's nothing to change, so the image doesn't change.

**Comment by imjasonh** [comment]
And what fortuitous timing, @mattmoor wrote a blog post about this topic! https://www.chainguard.dev/unchained/designing-build-date-epoch-in-chainguard-images 😁
