### ISSUE TITLE
`php-fpm`: stop using `options` for `entrypoint`

### ISSUE THREAD

**Issue by mattmoor** [chainguard-images/images#692]
![image](https://github.com/chainguard-images/images/assets/2442466/232a87a9-2c61-4173-8a28-9ddd9cb4eb60)

Currently `php-fpm` is the only image using `options` for anything other than adding packages, which we are moving to another mechanism entirely (trying to kill `options:` in `apko.yaml`).

We should split this "options"-based image to just be another config instead.

cc @imjasonh

**Comment by mattmoor** [comment]
related: https://github.com/chainguard-images/images/pull/691

**Comment by erikaheidi** [comment]
On it!
