### ISSUE TITLE
re: only latest and latest-dev tags are published to public tier

### ISSUE THREAD

**Issue by tuananh** [chainguard-images/images#815]
### Which image/versions are related to this issue/feature request?

> One of the upcoming changes we will notify users about is streamlining our catalog to only offer :latest tags for Images in the public tier. (including variants like :latest-dev).

> In 90 days on August 16, we will move all other tags, including version-specific tags, to the Standard and Custom catalog tiers. Using older versions of software [introduces](https://www.chainguard.dev/unchained/the-security-costs-of-base-image-version-squatting) potential security risks and it's our priority to ensure our free Image versions are held to the highest security standards.

As I understand it, we have no way to know the version of the software being packaged by looking at `latest` without pulling it and run it. can we tag the latest with the software version too?

eg. at any point, we will have `latest` and also tag it with the latest version of the software, eg `2.5`?

upon `2.6`, release, we will update latest, remove 2.5 and add `2.6` to latest.

** UPDATE**

On a second thought, removing existing tag can be very disruptive and will create bad user experience

**Comment by amouat** [comment]
This is a good question and we need to provide more advice here.

At the moment, you can find the version of all software in the image by looking at the SBOM. To find the version of the main package, try something like this:

```
$ cosign download sbom --platform=linux/amd64 cgr.dev/chainguard/nginx 2>/dev/null \
   | jq -r '.packages[] | select(.name == "nginx") | .versionInfo'

1.25.0-r0
```

That is grabbing the SBOM from the registry, so you'd want to use a digest here (make sure it's the digest of a platform specific image and not the index though). You can also get the SBOM out of the image e.g:

```
 $ id=$(docker create cgr.dev/chainguard/nginx) 
 $ docker cp $id:/var/lib/db/sbom/ ~/tmp/sbom
 $ ls ~/tmp/sbom
ca-certificates-bundle-20230506-r0.spdx.json libgcc-13.1.0-r1.spdx.json                   openssl-config-3.1.1-r0.spdx.json
glibc-2.37-r6.spdx.json                      libssl3-3.1.1-r0.spdx.json                   pcre-8.45-r0.spdx.json
glibc-locale-posix-2.37-r7.spdx.json         libstdc++-13.1.0-r1.spdx.json                wolfi-baselayout-20230201-r3.spdx.json
ld-linux-2.37-r7.spdx.json                   nginx-1.25.0-r0.spdx.json                    zlib-1.2.13-r3.spdx.json
libcrypto3-3.1.1-r0.spdx.json                nginx-package-config-1.25.0-r0.spdx.json
```

We realise this could be more straightforward. We’re looking into simpler solutions — such as putting the version into an annotations or label — and will also update the docs with these solutions and ways to integrate them into workflows.

**Comment by tuananh** [comment]
> such as putting the version into an annotations or label 

yes please

**Comment by amdawson** [comment]
Thanks for the feedback @tuananh , we are working on this and expect to have a plan in place before changing the way we publish tags.
