### ISSUE TITLE
PHP Sodium Extension

### ISSUE THREAD

**Issue by IshtarStar** [chainguard-images/images#818]
### Which image/versions are related to this issue/feature request?

php:latest-dev
php:latest-fpm-dev
php:latest-fpm
php:latest

### Issue/Feature description

Hello.

I recently made a pull request for wolfi, which has also already been merged into the main, to get the sodium extension which is already bundled into PHP since PHP 7.2.0.

I have contacted @erikaheidi to make sure that the latest PHP chainguard images will be updated.

Currently I do not see the sodium extension in the PHP images.

What do I have to do to update your Chainguard images based on Wolfi in your repository? 

https://github.com/wolfi-dev/os/pull/2441#event-9395651812
https://github.com/wolfi-dev/os/blob/main/php.yaml
https://twitter.com/DigitalMarcIT/status/1664143466908069888

**Comment by erikaheidi** [comment]
Hello @IshtarStar , apologies since I forgot to submit the patch to bump the package epoch. I just opened a new PR for that: https://github.com/wolfi-dev/os/pull/2618

Hopefully this will get merged today to be picked up by the nightly build.
