### ISSUE TITLE
docker error 132 with multi arch build

### ISSUE THREAD

**Issue by githubcdr** [chainguard-images/images#833]
### Which image/versions are related to this issue/feature request?

Hi,

I use colima to build amd64 images on my Macbook Air M1. This used to work fine, but for some reason I get error FATA[0006] exit status 132.

```
$ nerdctl run --rm -it cgr.dev/chainguard/wolfi-base:latest /bin/sh

cgr.dev/chainguard/wolfi-base:latest:                                             resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:416c9df6610e68a6e547d38dec0523cba0a40a8001c0aab3ade2f81e54960930:    done           |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:0bcbf1e2f885a73713a605f4455838e31b3f793a9f721deba0877a9445cb57e7: done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:9bd2a7e4c6c3e5dc7ccb4fa9c5d75d15deb4db10c3780b6733802d2ea61a474e:   done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:8a3d7aaf3eff8a064e82c5db7bf3a7027238237e54675c61398cb1da5956aa01:    done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 4.1 s                                                                    total:  5.4 Mi (1.3 MiB/s)
FATA[0006] exit status 132
```

Other images are working, am I doing something wrong? Did anything get changed in the base image? Same happens with cgr.dev/chainguard/python:3.11-dev image.

**Comment by githubcdr** [comment]
Hi, correct it should be amd64, since Colima is used for cross compiling.

But for some reason this image does not run correctly, but an nginx image does.

I had it running in older versions, will investigate if that still works.

**Comment by amouat** [comment]
For cross compiling, make sure you've registered the binfmt handlers e.g:

```
docker run --privileged --rm tonistiigi/binfmt --install all
```

If that fixes it, please let me know. I'm not quite sure if there's a difference between nerdctl and Docker here.

**Comment by amouat** [comment]
Ok. Let me know if you're able to recreate it and running the above doesn't help. I'll close this issue for the moment.

Thanks for the report.
