### ISSUE TITLE
Revision questsions.

### ISSUE THREAD

**Issue by kfox1111** [chainguard-images/images#881]
### Which image/versions are related to this issue/feature request?

I see some images have tags such as bash have tags such as:
5
5.2
5.2.15
5.2.15-r2

are the ones with revision numbers such as 5.2.15-r2 immutable? There a reason some of the revisions are missing such as -r1 there? Do revisions get removed or was -r1 just never uploaded due to it being broken?

**Comment by imjasonh** [comment]
Yeah I think what happened is that we added the bash image after -r2 was added, so that was the latest (and so far only) image to get built and tagged.

If an -r3 is built (or 5.2.16 or 5.3 or 6) I'd expect to see new tags for those.

**Comment by amouat** [comment]
Yes, I think that's accurate.

If you want an immutable tag, we'd recommend you use the digest e.g:

```
docker pull cgr.dev/chainguard/bash:latest@sha256:6d05cf7eb51324b5e87bd6ef7699a963af76957644dc153aa663d1d21523a6a9
```

**Comment by amouat** [comment]
I think this can be closed, please open a new issue if you have any further questions @kfox1111 .
