### ISSUE TITLE
Redis SBOM is missing

### ISSUE THREAD

**Issue by stefanprodan** [chainguard-images/images#893]
### Which image/versions are related to this issue/feature request?

cgr.dev/chainguard/redis

### Issue/Feature description

Trying to download the SBOM fails for Redis while it works for NGINX. 

```console
$ cosign download sbom  cgr.dev/chainguard/redis --platform linux/amd64
WARNING: Downloading SBOMs this way does not ensure its authenticity. If you want to ensure a tamper-proof SBOM, download it using 'cosign download attestation <image uri>' or verify its signature using 'cosign verify --key <key path> --attachment sbom <image uri>'.

This multiarch image does not have an SBOM attached at the index level.
Try using --platform with one of the following architectures:
linux/amd64, linux/arm64

Error: no SBOM found attached to image index
main.go:74: error during command execution: no SBOM found attached to image index
```

**Comment by mattmoor** [comment]
The SBOMs are published as attestations.  For example [this](https://explore.ggcr.dev/?blob=cgr.dev%2Fchainguard%2Fredis%40sha256%3A27407c594fa48d49f18fdb8b761e71998aac2656b2c4f3449a2c0246e52ed7cd&jq=.payload&jq=base64+-d&jq=jq&mt=application%2Fvnd.dsse.envelope.v1%2Bjson&size=5028) is the SBOM for the latest `redis` image (as of now).

You should be able to use `cosign download attestation` (as the warning recommends) to get the signed SBOM.

**Comment by amouat** [comment]
Just to follow-up on this, if you're using the latest cosign from source (e.g. via go install), you can do:

```
$(go env GOPATH)/bin/cosign download attestation --platform=linux/amd64 --predicate-type=https://spdx.dev/Document cgr.dev/chainguard/redis | jq -r .payload | base64 -d`
```
