### ISSUE TITLE
[go] Go version 18?

### ISSUE THREAD

**Issue by twocs** [chainguard-images/images#90]
Feels a bit selfish to ask for a go 1.18 version, and was looking into building my own image. 

But then I noticed that Apko itself is currently built with go 1.18. Would it be possible to have a 1.18 tagged version? (We are considering upgrading soon, but there is a very minor issue that 1.19 now has an extra OmitHost bool field in the url.URL payload).

Go version 1.18 wil continue to be supported until the 1.20 release, likely around February 2023. Please close this issue if there is any good reason that go version 1.18.6 is not supported.

**Comment by gerhard** [comment]
I was looking for something similar, specifically `cgr.dev/chainguard/go:1.19`. Any plans to tag specific `go` minors?

**Comment by amouat** [comment]
@gerhard I'm sorry this isn't more obvious right now, but that image does exist:

`docker pull cgr.dev/chainguard/go:1.19`

We have an update coming on what major and minor versions of images we will be supporting going forward (across all images)

**Comment by amouat** [comment]
This should work now. Apologies for the delay.

```
docker pull cgr.dev/chainguard/go:1.1
```
