### ISSUE TITLE
[jdk] Consider packaging just JRE

### ISSUE THREAD

**Issue by sideeffffect** [chainguard-images/images#91]
Consider please also having a flavor/variant of this image which contains only the JRE (runtime environment), not the whole big JDK.
The image will be much smaller.

E.g. https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.4.1%2B1/OpenJDK17U-jre_x64_alpine-linux_hotspot_17.0.4.1_1.tar.gz

**Comment by jdolitsky** [comment]
I believe this can be closed now that we have [jre](https://github.com/chainguard-images/images/blob/main/images/jre) ?

**Comment by amouat** [comment]
Yes, thanks.
