### ISSUE TITLE
[nginx] dependencies pulling in /bin/sh and more

### ISSUE THREAD

**Issue by damianoneill** [chainguard-images/images#92]
Apologies if this is a stupid question.  

I'm looking for a distroless nginx image and came across your repo while googling.  I've pulled the image down and looked inside to see what contents are bundled.  

I noted a lot of binaries in the /bin, /sbin directories, are these needed to execute nginx?  If not is there a plan to produce a version of this image that doesn't include them? 

Thanks in advance,
Damian.

**Comment by patflynn** [comment]
@amouat any thoughts on this issue. Sounds like we need the shell. Should we close or are there followups?

**Comment by amouat** [comment]
Sounds good, but add we should add to the docs why the shell is there.

**Comment by amouat** [comment]
This seems to have been fixed for a while. There's no shell now anyway.
