### ISSUE TITLE
[python] Couldn't run executables

### ISSUE THREAD

**Issue by thowbik-dustan** [chainguard-images/images#98]
```Dockerfile
#-----------------------STAGE 1------------------------------------
FROM python:3.10.7-slim-buster as build_image

RUN apt-get update && apt-get -y upgrade && \
    apt-get install -y gcc

#-----------------------STAGE 2-----------------------------------
FROM cgr.dev/chainguard/python:latest

COPY --from=build_image /usr/bin/gcc /usr/bin/gcc

ENTRYPOINT ["gcc", "--help"]
```

I build a docker image with the above `Dockerfile` and I'm getting the below mentioned error when I run that docker image

```bash
exec /usr/bin/gcc: no such file or directory
```

The file is copied successfully, I checked with dive tool for the layer change. Please refer the below image

![image](https://user-images.githubusercontent.com/110883919/205346320-01a84bc0-6b6d-4495-b29e-a8cdcc52620b.png)

Sorry if this is a silly mistake but can you guys help ?. I couldn't execute any binary files I copy. I tested this same method with [google's distroless image](https://github.com/GoogleContainerTools/distroless/blob/main/experimental/python3/README.md), It works fine and I get the help menu.

**NOTE** : _Why I'm using python image is, I actually tried to execute `uwsgi` binary for running python flask. But I mentioned `gcc --help` for simple POC_

**Comment by amouat** [comment]
Unfortunately, this isn't the right way to do things. In general you can't copy over programs like this unless they've been statically compiled to include all their dependencies.

In this case, I'm afraid the best approach is to build a new python image with gcc installed. To do this, you would add `gcc` to the list of packages in https://github.com/chainguard-images/images/blob/main/images/python/configs/latest-glibc.apko.yaml and run a new build with apko (see https://edu.chainguard.dev/open-source/apko/getting-started-with-apko/ for instructions).

In the future, we could have an "sdk" variant of the image that includes tools like gcc. We don't want to put gcc in the base image for size reasons.
